import { useCallback, useEffect, useState } from 'react';
import { catalogApi } from '../../api/catalogApi.js';
import { purchasingApi } from '../../api/purchasingApi.js';
import { researchApi } from '../../api/researchApi.js';
import BusinessTerm from '../../components/BusinessTerm.jsx';
import { ErrorState, LoadingState, PageHeader } from '../../components/catalog/CatalogStates.jsx';
import SampleEvaluationForm from '../../components/research/SampleEvaluationForm.jsx';
import UnitEconomicsCalculator from '../../components/research/UnitEconomicsCalculator.jsx';
import { money, percent, researchTerms } from '../../components/research/ResearchTerms.js';

const nextStatuses = {
  research: ['shortlisted', 'rejected'], shortlisted: ['research', 'sourcing', 'rejected'],
  sourcing: ['shortlisted', 'sampling', 'rejected'], sampling: ['sourcing', 'approved', 'rejected'],
  approved: ['sampling', 'rejected'], rejected: ['research'], launched: [],
};

export default function ResearchCandidateDetailPage({ organizationId, candidateId }) {
  const [candidate, setCandidate] = useState(null);
  const [categories, setCategories] = useState([]);
  const [suppliers, setSuppliers] = useState([]);
  const [error, setError] = useState(null);
  const [notice, setNotice] = useState(null);
  const [stage, setStage] = useState('');
  const [snapshot, setSnapshot] = useState({ marketplace: '', listingUrl: '', sellingPrice: '', currency: 'EGP', rating: '', reviewCount: '', demandScore: '', competitionScore: '', evidenceNotes: '' });
  const [supplier, setSupplier] = useState({ supplierId: '', leadName: '', contactUrl: '', quotedUnitCost: '', currency: 'EGP', moq: '1', leadTimeDays: '0', quoteDate: '', preferred: true, notes: '' });
  const [evaluation, setEvaluation] = useState({ recommendation: 'needs_more_research', riskLevel: 'medium', targetSellingPrice: '', targetUnitCost: '', targetMarginPercentage: '', targetRoiPercentage: '', launchQuantity: '', plannedCapital: '', projectedProfit: '', rationale: '' });
  const [conversion, setConversion] = useState({ categoryId: '', brandId: '', productName: '', modelNumber: '', description: '', variantName: 'Standard', skuCode: '', manufacturerPartNumber: '', serialTrackingEnabled: false });
  const [fee, setFee] = useState({ feeName: '', feeType: 'percentage', feeValue: '', currency: '', effectiveFrom: '', sourceUrl: '', notes: '' });
  const [evidence, setEvidence] = useState({ evidenceType: 'url', title: '', sourceUrl: '', storageKey: '', notes: '' });

  const load = useCallback(async () => {
    try {
      const [candidateResult, categoryResult, supplierResult] = await Promise.all([
        researchApi.getCandidate(organizationId, candidateId),
        catalogApi.listCategories(organizationId),
        purchasingApi.listSuppliers(organizationId, { limit: 100, isActive: true }),
      ]);
      const value = candidateResult.data;
      setCandidate(value); setCategories(categoryResult.data); setSuppliers(supplierResult.data); setStage('');
      setConversion((current) => ({ ...current, categoryId: value.category_id || '', productName: value.name, description: value.notes || '', skuCode: value.name.toUpperCase().replace(/[^A-Z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 48) + '-01' }));
      const latest = value.economics[0];
      if (latest) setEvaluation((current) => ({ ...current, unitEconomicsId: latest.id, targetSellingPrice: latest.selling_price, targetUnitCost: latest.supplier_unit_cost, targetMarginPercentage: latest.net_margin_percentage, targetRoiPercentage: latest.roi_percentage }));
      setError(null);
    } catch (requestError) { setError(requestError); }
  }, [organizationId, candidateId]);
  useEffect(() => {
    const timer = setTimeout(load, 0);
    return () => clearTimeout(timer);
  }, [load]);

  async function action(operation, success) {
    setError(null); setNotice(null);
    try { const result = await operation(); setNotice(success); await load(); return result; }
    catch (requestError) { setError(requestError); return null; }
  }

  function change(setter, field, value) { setter((current) => ({ ...current, [field]: value })); }
  if (error && !candidate) return <ErrorState error={error} />;
  if (!candidate) return <LoadingState label="Loading candidate workspace…" />;
  const latestEconomics = candidate.economics[0];

  return <>
    <PageHeader eyebrow="Research candidate" title={candidate.name} description={candidate.notes || 'No candidate notes yet.'} action={<div className="header-actions"><a className="secondary-button" href="#research/candidates">All candidates</a>{candidate.marketplace_url && <a className="secondary-button" href={candidate.marketplace_url} target="_blank" rel="noreferrer">Marketplace evidence</a>}</div>} />
    {notice && <div className="success-banner">{notice}</div>}{error && <div className="form-error" role="alert">{error.message}</div>}
    <section className="candidate-stage-panel"><div><span className={'status-pill ' + candidate.status}>{candidate.status}</span><strong>{candidate.category_name || 'Uncategorized'}</strong><small>{candidate.brand_name || 'No candidate brand'}</small></div>{nextStatuses[candidate.status].length > 0 && <form onSubmit={(event) => { event.preventDefault(); action(() => researchApi.patchCandidate(organizationId, candidateId, { status: stage }), 'Candidate status updated.'); }}><label>Move candidate<select required value={stage} onChange={(event) => setStage(event.target.value)}><option value="">Choose next status</option>{nextStatuses[candidate.status].map((status) => <option key={status} value={status}>{status}</option>)}</select></label><button className="secondary-button">Update status</button></form>}</section>

    <div className="detail-grid research-detail-grid">
      <section className="detail-card"><h2>Market snapshot</h2><form className="embedded-form" onSubmit={(event) => { event.preventDefault(); action(() => researchApi.createSnapshot(organizationId, candidateId, { ...snapshot, sellingPrice: snapshot.sellingPrice || null, rating: snapshot.rating || undefined, reviewCount: snapshot.reviewCount || undefined, demandScore: snapshot.demandScore || undefined, competitionScore: snapshot.competitionScore || undefined, evidenceNotes: snapshot.evidenceNotes || null }), 'Market snapshot saved.'); }}><div className="form-grid two-columns"><label>Marketplace<input required value={snapshot.marketplace} onChange={(event) => change(setSnapshot, 'marketplace', event.target.value)} /></label><label>Listing URL<input required type="url" value={snapshot.listingUrl} onChange={(event) => change(setSnapshot, 'listingUrl', event.target.value)} /></label><label>Selling price<input type="number" min="0" step="0.0001" value={snapshot.sellingPrice} onChange={(event) => change(setSnapshot, 'sellingPrice', event.target.value)} /></label><label>Currency<input value={snapshot.currency} onChange={(event) => change(setSnapshot, 'currency', event.target.value.toUpperCase())} /></label><label>Rating<input type="number" min="0" max="5" step="0.1" value={snapshot.rating} onChange={(event) => change(setSnapshot, 'rating', event.target.value)} /></label><label>Reviews<input type="number" min="0" value={snapshot.reviewCount} onChange={(event) => change(setSnapshot, 'reviewCount', event.target.value)} /></label><label>Demand score<input type="number" min="1" max="5" value={snapshot.demandScore} onChange={(event) => change(setSnapshot, 'demandScore', event.target.value)} /></label><label>Competition score<input type="number" min="1" max="5" value={snapshot.competitionScore} onChange={(event) => change(setSnapshot, 'competitionScore', event.target.value)} /></label></div><button className="primary-button">Add snapshot</button></form>{candidate.snapshots.length > 0 && <div className="history-list compact-history">{candidate.snapshots.map((item) => <article key={item.id}><div><strong>{item.marketplace}</strong><a href={item.listing_url} target="_blank" rel="noreferrer">Open source</a></div><div>{money(item.selling_price, item.currency || 'EGP')}<small>{item.rating ? item.rating + '★ · ' + item.review_count + ' reviews' : new Date(item.observed_at).toLocaleDateString()}</small></div></article>)}</div>}</section>

      <section className="detail-card"><h2>Supplier options</h2><form className="embedded-form" onSubmit={(event) => { event.preventDefault(); action(() => researchApi.createSupplierOption(organizationId, candidateId, { supplierId: supplier.supplierId || null, leadName: supplier.leadName || null, contactUrl: supplier.contactUrl || null, quotedUnitCost: supplier.quotedUnitCost, currency: supplier.currency, moq: supplier.moq, leadTimeDays: Number(supplier.leadTimeDays), quoteDate: supplier.quoteDate || null, preferred: supplier.preferred, notes: supplier.notes || null }), 'Supplier option saved.'); }}><div className="form-grid two-columns"><label>Existing supplier<select value={supplier.supplierId} onChange={(event) => change(setSupplier, 'supplierId', event.target.value)}><option value="">Use a temporary lead</option>{suppliers.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Temporary lead<input value={supplier.leadName} onChange={(event) => change(setSupplier, 'leadName', event.target.value)} /></label><label>Quoted unit cost<input required type="number" min="0" step="0.0001" value={supplier.quotedUnitCost} onChange={(event) => change(setSupplier, 'quotedUnitCost', event.target.value)} /></label><label>Currency<input required value={supplier.currency} onChange={(event) => change(setSupplier, 'currency', event.target.value.toUpperCase())} /></label><label><BusinessTerm term="MOQ" explanation={researchTerms.MOQ} /><input required type="number" min="0.0001" step="0.0001" value={supplier.moq} onChange={(event) => change(setSupplier, 'moq', event.target.value)} /></label><label><BusinessTerm term="Lead Time" explanation={researchTerms['Lead Time']} /><input required type="number" min="0" value={supplier.leadTimeDays} onChange={(event) => change(setSupplier, 'leadTimeDays', event.target.value)} /></label><label>Quote date<input type="date" value={supplier.quoteDate} onChange={(event) => change(setSupplier, 'quoteDate', event.target.value)} /></label><label className="checkbox-field"><input type="checkbox" checked={supplier.preferred} onChange={(event) => change(setSupplier, 'preferred', event.target.checked)} />Preferred option</label></div><button className="primary-button">Add supplier option</button></form>{candidate.suppliers.length > 0 && <div className="history-list compact-history">{candidate.suppliers.map((item) => <article key={item.id}><div><strong>{item.supplier_name || item.lead_name}</strong><small>{item.preferred ? 'Preferred' : 'Alternative'} · MOQ {Number(item.moq)} · {item.lead_time_days} days</small></div><div>{money(item.quoted_unit_cost, item.currency)}</div></article>)}</div>}</section>

      <section className="detail-card span-two"><div className="detail-card-heading"><div><p className="eyebrow">Flexible checklist</p><h2>Product sample evaluation</h2></div><span>{candidate.samples.length} samples</span></div><SampleEvaluationForm supplierOptions={candidate.suppliers} onSubmit={(body) => action(() => researchApi.createSample(organizationId, candidateId, body), 'Sample evaluation saved.')} />{candidate.samples.length > 0 && <div className="history-list">{candidate.samples.map((sample) => <article key={sample.id}><div><strong>{sample.reference_code || 'Unnumbered sample'}</strong><small>{sample.checklist.length} checks · {sample.notes || 'No notes'}</small></div><span className={'status-pill ' + sample.result}>{sample.result}</span></article>)}</div>}</section>

      <UnitEconomicsCalculator onCalculate={async (body) => {
        const result = await action(() => researchApi.calculateEconomics(organizationId, candidateId, body), 'Unit economics calculated and saved.');
        if (!result) throw new Error('Unit economics could not be calculated.');
        return result.data;
      }} />

      <section className="detail-card"><h2>Launch evaluation</h2><form className="embedded-form" onSubmit={(event) => { event.preventDefault(); action(() => researchApi.createEvaluation(organizationId, candidateId, { ...evaluation, unitEconomicsId: evaluation.unitEconomicsId || null }), 'Launch evaluation saved.'); }}><div className="form-grid two-columns"><label>Recommendation<select value={evaluation.recommendation} onChange={(event) => change(setEvaluation, 'recommendation', event.target.value)}><option value="buy">Buy</option><option value="maybe">Maybe</option><option value="reject">Reject</option><option value="needs_more_research">Needs more research</option></select></label><label>Risk<select value={evaluation.riskLevel} onChange={(event) => change(setEvaluation, 'riskLevel', event.target.value)}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label>{[['targetSellingPrice', 'Target selling price'], ['targetUnitCost', 'Target unit cost'], ['targetMarginPercentage', 'Target margin %'], ['targetRoiPercentage', 'Target ROI %'], ['launchQuantity', 'Launch quantity'], ['plannedCapital', 'Planned capital'], ['projectedProfit', 'Projected profit']].map(([field, label]) => <label key={field}>{label}<input required type="number" step="0.0001" min={field === 'projectedProfit' || field.includes('Percentage') ? undefined : '0'} value={evaluation[field]} onChange={(event) => change(setEvaluation, field, event.target.value)} /></label>)}</div><label>Decision rationale<textarea required minLength="3" rows="3" value={evaluation.rationale} onChange={(event) => change(setEvaluation, 'rationale', event.target.value)} /></label><button className="primary-button">Save launch decision</button></form>{candidate.evaluations.length > 0 && <div className="decision-summary"><strong>{candidate.evaluations[0].recommendation.replaceAll('_', ' ')}</strong><span>{candidate.evaluations[0].risk_level} risk</span><small>{percent(candidate.evaluations[0].target_margin_percentage)} margin · {money(candidate.evaluations[0].planned_capital, latestEconomics?.currency || 'EGP')} planned</small></div>}</section>

      <section className="detail-card"><h2>Fee assumption history</h2><form className="embedded-form" onSubmit={(event) => { event.preventDefault(); action(() => researchApi.createFeeAssumption(organizationId, candidateId, { ...fee, currency: fee.currency || null, sourceUrl: fee.sourceUrl || null, notes: fee.notes || null }), 'Fee assumption saved.'); }}><div className="form-grid two-columns"><label>Fee name<input required value={fee.feeName} onChange={(event) => change(setFee, 'feeName', event.target.value)} /></label><label>Type<select value={fee.feeType} onChange={(event) => change(setFee, 'feeType', event.target.value)}><option value="percentage">Percentage</option><option value="fixed">Fixed</option></select></label><label>Value<input required type="number" min="0" step="0.0001" value={fee.feeValue} onChange={(event) => change(setFee, 'feeValue', event.target.value)} /></label><label>Effective from<input required type="date" value={fee.effectiveFrom} onChange={(event) => change(setFee, 'effectiveFrom', event.target.value)} /></label><label className="span-two">Source URL<input type="url" value={fee.sourceUrl} onChange={(event) => change(setFee, 'sourceUrl', event.target.value)} /></label></div><button className="secondary-button">Add fee assumption</button></form>{candidate.feeAssumptions.map((item) => <p className="form-note" key={item.id}>{item.fee_name}: {Number(item.fee_value)}{item.fee_type === 'percentage' ? '%' : ' ' + (item.currency || '')} · {item.effective_from}</p>)}</section>

      <section className="detail-card"><h2>Evidence metadata</h2><p className="form-note">Files and screenshots use external storage metadata; binary data is never stored in PostgreSQL.</p><form className="embedded-form" onSubmit={(event) => { event.preventDefault(); action(() => researchApi.createEvidence(organizationId, candidateId, { ...evidence, sourceUrl: evidence.sourceUrl || null, storageKey: evidence.storageKey || null, notes: evidence.notes || null }), 'Evidence metadata saved.'); }}><div className="form-grid two-columns"><label>Type<select value={evidence.evidenceType} onChange={(event) => change(setEvidence, 'evidenceType', event.target.value)}><option value="url">URL</option><option value="file">File metadata</option><option value="screenshot">Screenshot metadata</option></select></label><label>Title<input required value={evidence.title} onChange={(event) => change(setEvidence, 'title', event.target.value)} /></label><label>Source URL<input type="url" value={evidence.sourceUrl} onChange={(event) => change(setEvidence, 'sourceUrl', event.target.value)} /></label><label>Storage key<input value={evidence.storageKey} onChange={(event) => change(setEvidence, 'storageKey', event.target.value)} /></label></div><button className="secondary-button">Add evidence</button></form></section>
    </div>

    {candidate.status === 'approved' && <section className="conversion-panel"><div><p className="eyebrow">Explicit catalog conversion</p><h2>Create Product from Candidate</h2><p>Review the Product, Variant, and SKU. This transaction creates no supplier-product link, inventory movement, or purchase order.</p></div><form onSubmit={(event) => { event.preventDefault(); action(() => researchApi.createProduct(organizationId, candidateId, { ...conversion, categoryId: conversion.categoryId, brandId: conversion.brandId || null, modelNumber: conversion.modelNumber || null, description: conversion.description || null, manufacturerPartNumber: conversion.manufacturerPartNumber || null }), 'Draft product created successfully.'); }}><div className="form-grid three-columns"><label>Product name<input required value={conversion.productName} onChange={(event) => change(setConversion, 'productName', event.target.value)} /></label><label>Category<select required value={conversion.categoryId} onChange={(event) => change(setConversion, 'categoryId', event.target.value)}><option value="">Choose category</option>{categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Variant name<input required value={conversion.variantName} onChange={(event) => change(setConversion, 'variantName', event.target.value)} /></label><label>SKU code<input required value={conversion.skuCode} onChange={(event) => change(setConversion, 'skuCode', event.target.value.toUpperCase())} /></label><label>Model number<input value={conversion.modelNumber} onChange={(event) => change(setConversion, 'modelNumber', event.target.value)} /></label><label className="checkbox-field"><input type="checkbox" checked={conversion.serialTrackingEnabled} onChange={(event) => change(setConversion, 'serialTrackingEnabled', event.target.checked)} />Serial tracking foundation</label></div><button className="primary-button">Create Product from Candidate</button></form></section>}
    {candidate.status === 'launched' && <section className="conversion-panel"><div><p className="eyebrow">Converted</p><h2>Candidate is linked to a draft product</h2><p>The research history remains intact and the conversion cannot be repeated.</p></div><a className="primary-button" href={'#products/' + candidate.catalog_product_id}>Open catalog product</a></section>}
  </>;
}
